# Generated by Django 3.1.2 on 2021-01-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('fundacao', models.TextField()),
                ('carioca', models.TextField()),
                ('brasileiro', models.TextField()),
                ('copadobrasil', models.TextField()),
                ('libertadores', models.TextField()),
            ],
        ),
    ]
