# Generated by Django 3.1.2 on 2021-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='mundial',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='brasileiro',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='carioca',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='copadobrasil',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='fundacao',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='libertadores',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=250),
        ),
    ]
