# Generated by Django 3.1.7 on 2021-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasico', '0005_equipe_sulamericana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo7')),
                ('nome', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
