# Generated by Django 3.1.7 on 2021-04-09 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appbasico', '0007_auto_20210407_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo7'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='post',
            field=models.CharField(default='', max_length=140),
        ),
    ]
