# Generated by Django 3.1.7 on 2021-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasico', '0009_remove_postagem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='time',
            field=models.CharField(default='', max_length=140),
        ),
    ]
